services:
  # Backend Service
  - type: web
    name: ufc-fan-app-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: STRIPE_SECRET_KEY
        sync: false  # This will be set in Render dashboard
      - key: STRIPE_WEBHOOK_SECRET
        sync: false  # This will be set in Render dashboard
      - key: MONGODB_URI
        sync: false  # This will be set in Render dashboard if you're using MongoDB

  # Frontend Service
  - type: web
    name: ufc-fan-app-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: REACT_APP_STRIPE_PUBLISHABLE_KEY
        sync: false  # This will be set in Render dashboard
      - key: REACT_APP_STRIPE_PRICE_ID
        sync: false  # This will be set in Render dashboard
      - key: REACT_APP_API_URL
        value: https://ufc-fan-app-backend.onrender.com


